### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by Abubabubi** [stoeffel/elm-verify-examples#98]
Unable to install latest elm-verify examples due to unsupported elm-test/elmi-to-json dependency.
```error /Users/gantz/conta/front-end/node_modules/elmi-to-json: Command failed.
Exit code: 1
Command: binwrap-install
Arguments: 
Directory: /Users/gantz/conta/front-end/node_modules/elmi-to-json
Output:
/Users/gantz/conta/front-end/node_modules/elmi-to-json/node_modules/binwrap/install.js:18
    throw new Error("No binaries are available for your platform: " + buildId);
    ^

Error: No binaries are available for your platform: darwin-arm64
    at install (/Users/gantz/conta/front-end/node_modules/elmi-to-json/node_modules/binwrap/install.js:18:11)
    at Object.install (/Users/gantz/conta/front-end/node_modules/elmi-to-json/node_modules/binwrap/index.js:14:14)
    at Object.<anonymous> (/Users/gantz/conta/front-end/node_modules/elmi-to-json/node_modules/binwrap/bin/binwrap-install:18:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front-end@0.0.1 yarn:update: `bash config/scripts/install-yarn && build/yarn/bin/yarn`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the front-end@0.0.1 yarn:update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```.

**Comment by lydell** [comment]
elm-verify-examples depends on elm-test, which in turn used to depend on elmi-to-json. This is not an issue anymore since elm-test no longer uses elmi-to-json.

**Comment by gampleman** [comment]
So @lydell this can be closed right?
